### PR TITLE
Homescreen , Listdisplay

### PR DESCRIPTION
**Pull request by SiminyA**
1. Display of expense summary , category wise expense in Home screen
2. Adjusted the divider value between the list items - Home screen & Expenses screen

### CODE REVIEW

**Review by lakshmiathi — APPROVED** [review]
Its good to have this summary in home page.

**Comment by danieltanyi** [comment]
I think it looks good to see the expense summary display in the Home page

**Review by madhulikavecha — CHANGES_REQUESTED** [review]
please change the comments

**Comment by madhulikavecha** [comment]
looks . good

**Pull request merged**
